### ISSUE TITLE
Model Boyutu

### ISSUE THREAD

**Issue by myKemal** [cananmuzennet/girismodali1#1]
Modal'ın sayfanın tamamnını kapatıyor. Tamamını kapatmamalı. Bootstrap örnreğindeki ölçüler uygun

**Comment by cananmuzennet** [comment]
![modalfoto](https://github.com/cananmuzennet/girismodali1/assets/147536168/7ceaa32c-0cba-4664-96a9-3d35bd3107f4)
 Hocam modal bende böyle gözüyor diğer arkadaşlarda da denedik onlarda da bende ki gibi gözüküyor
